# This is a basic workflow to help you get started with Actions

name: Excavator

on:
    schedule:
        - cron: '0 */8 * * *'

jobs:
    excavate:
        name: Excavate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Excavate
              uses: integzz/Scoop-GithubActions@stable
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SKIP_UPDATED: '1'
