name: Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  issueHandler:
    runs-on: ubuntu-latest
    name: Issue Handler
    steps:
      - uses: actions/checkout@main
      - name: Issue Handler
        uses: integzz/Scoop-GithubActions@stable
        if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
