name: Commented Pull Request

on:
  issue_comment:
    types: [created]

jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Pull Request Validation
        uses: integzz/Scoop-GithubActions@stable
        if: startsWith(github.event.comment.body, '/verify')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
