name: Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Pull Request Validation
        uses: integzz/Scoop-GithubActions@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
