name: Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  pullRequestHandler:
    name: Pull Request Handler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Pull Request Handler
        uses: Ash258/Scoop-GithubActions@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
