name: Excavator

on:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  excavate:
    name: Excavator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: integzz/Scoop-GithubActions@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
